// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// WeightsColumns holds the columns for the "weights" table.
	WeightsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "userid", Type: field.TypeInt64},
		{Name: "timestamp", Type: field.TypeTime},
		{Name: "value", Type: field.TypeFloat64},
	}
	// WeightsTable holds the schema information for the "weights" table.
	WeightsTable = &schema.Table{
		Name:       "weights",
		Columns:    WeightsColumns,
		PrimaryKey: []*schema.Column{WeightsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "weight_userid_timestamp",
				Unique:  true,
				Columns: []*schema.Column{WeightsColumns[1], WeightsColumns[2]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		WeightsTable,
	}
)

func init() {
}
