// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Bundle is the predicate function for bundle builders.
type Bundle func(*sql.Selector)

// Food is the predicate function for food builders.
type Food func(*sql.Selector)

// Journal is the predicate function for journal builders.
type Journal func(*sql.Selector)

// UserSettings is the predicate function for usersettings builders.
type UserSettings func(*sql.Selector)

// Weight is the predicate function for weight builders.
type Weight func(*sql.Selector)
