// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// UserSettings is the predicate function for usersettings builders.
type UserSettings func(*sql.Selector)

// Weight is the predicate function for weight builders.
type Weight func(*sql.Selector)
