// Code generated by ent, DO NOT EDIT.

package bundle

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the bundle type in the database.
	Label = "bundle"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserid holds the string denoting the userid field in the database.
	FieldUserid = "userid"
	// FieldKey holds the string denoting the key field in the database.
	FieldKey = "key"
	// FieldData holds the string denoting the data field in the database.
	FieldData = "data"
	// Table holds the table name of the bundle in the database.
	Table = "bundles"
)

// Columns holds all SQL columns for bundle fields.
var Columns = []string{
	FieldID,
	FieldUserid,
	FieldKey,
	FieldData,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Bundle queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserid orders the results by the userid field.
func ByUserid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserid, opts...).ToFunc()
}

// ByKey orders the results by the key field.
func ByKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldKey, opts...).ToFunc()
}
