// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"sync"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/devldavydov/myfood/internal/storage/ent/predicate"
	"github.com/devldavydov/myfood/internal/storage/ent/weight"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeWeight = "Weight"
)

// WeightMutation represents an operation that mutates the Weight nodes in the graph.
type WeightMutation struct {
	config
	op            Op
	typ           string
	id            *int
	userid        *int64
	adduserid     *int64
	timestamp     *time.Time
	value         *float64
	addvalue      *float64
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*Weight, error)
	predicates    []predicate.Weight
}

var _ ent.Mutation = (*WeightMutation)(nil)

// weightOption allows management of the mutation configuration using functional options.
type weightOption func(*WeightMutation)

// newWeightMutation creates new mutation for the Weight entity.
func newWeightMutation(c config, op Op, opts ...weightOption) *WeightMutation {
	m := &WeightMutation{
		config:        c,
		op:            op,
		typ:           TypeWeight,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withWeightID sets the ID field of the mutation.
func withWeightID(id int) weightOption {
	return func(m *WeightMutation) {
		var (
			err   error
			once  sync.Once
			value *Weight
		)
		m.oldValue = func(ctx context.Context) (*Weight, error) {
			once.Do(func() {
				if m.done {
					err = errors.New("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().Weight.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withWeight sets the old Weight of the mutation.
func withWeight(node *Weight) weightOption {
	return func(m *WeightMutation) {
		m.oldValue = func(context.Context) (*Weight, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m WeightMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m WeightMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, errors.New("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *WeightMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// IDs queries the database and returns the entity ids that match the mutation's predicate.
// That means, if the mutation is applied within a transaction with an isolation level such
// as sql.LevelSerializable, the returned ids match the ids of the rows that will be updated
// or updated by the mutation.
func (m *WeightMutation) IDs(ctx context.Context) ([]int, error) {
	switch {
	case m.op.Is(OpUpdateOne | OpDeleteOne):
		id, exists := m.ID()
		if exists {
			return []int{id}, nil
		}
		fallthrough
	case m.op.Is(OpUpdate | OpDelete):
		return m.Client().Weight.Query().Where(m.predicates...).IDs(ctx)
	default:
		return nil, fmt.Errorf("IDs is not allowed on %s operations", m.op)
	}
}

// SetUserid sets the "userid" field.
func (m *WeightMutation) SetUserid(i int64) {
	m.userid = &i
	m.adduserid = nil
}

// Userid returns the value of the "userid" field in the mutation.
func (m *WeightMutation) Userid() (r int64, exists bool) {
	v := m.userid
	if v == nil {
		return
	}
	return *v, true
}

// OldUserid returns the old "userid" field's value of the Weight entity.
// If the Weight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WeightMutation) OldUserid(ctx context.Context) (v int64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldUserid is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldUserid requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldUserid: %w", err)
	}
	return oldValue.Userid, nil
}

// AddUserid adds i to the "userid" field.
func (m *WeightMutation) AddUserid(i int64) {
	if m.adduserid != nil {
		*m.adduserid += i
	} else {
		m.adduserid = &i
	}
}

// AddedUserid returns the value that was added to the "userid" field in this mutation.
func (m *WeightMutation) AddedUserid() (r int64, exists bool) {
	v := m.adduserid
	if v == nil {
		return
	}
	return *v, true
}

// ResetUserid resets all changes to the "userid" field.
func (m *WeightMutation) ResetUserid() {
	m.userid = nil
	m.adduserid = nil
}

// SetTimestamp sets the "timestamp" field.
func (m *WeightMutation) SetTimestamp(t time.Time) {
	m.timestamp = &t
}

// Timestamp returns the value of the "timestamp" field in the mutation.
func (m *WeightMutation) Timestamp() (r time.Time, exists bool) {
	v := m.timestamp
	if v == nil {
		return
	}
	return *v, true
}

// OldTimestamp returns the old "timestamp" field's value of the Weight entity.
// If the Weight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WeightMutation) OldTimestamp(ctx context.Context) (v time.Time, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldTimestamp is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldTimestamp requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldTimestamp: %w", err)
	}
	return oldValue.Timestamp, nil
}

// ResetTimestamp resets all changes to the "timestamp" field.
func (m *WeightMutation) ResetTimestamp() {
	m.timestamp = nil
}

// SetValue sets the "value" field.
func (m *WeightMutation) SetValue(f float64) {
	m.value = &f
	m.addvalue = nil
}

// Value returns the value of the "value" field in the mutation.
func (m *WeightMutation) Value() (r float64, exists bool) {
	v := m.value
	if v == nil {
		return
	}
	return *v, true
}

// OldValue returns the old "value" field's value of the Weight entity.
// If the Weight object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *WeightMutation) OldValue(ctx context.Context) (v float64, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, errors.New("OldValue is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, errors.New("OldValue requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldValue: %w", err)
	}
	return oldValue.Value, nil
}

// AddValue adds f to the "value" field.
func (m *WeightMutation) AddValue(f float64) {
	if m.addvalue != nil {
		*m.addvalue += f
	} else {
		m.addvalue = &f
	}
}

// AddedValue returns the value that was added to the "value" field in this mutation.
func (m *WeightMutation) AddedValue() (r float64, exists bool) {
	v := m.addvalue
	if v == nil {
		return
	}
	return *v, true
}

// ResetValue resets all changes to the "value" field.
func (m *WeightMutation) ResetValue() {
	m.value = nil
	m.addvalue = nil
}

// Where appends a list predicates to the WeightMutation builder.
func (m *WeightMutation) Where(ps ...predicate.Weight) {
	m.predicates = append(m.predicates, ps...)
}

// WhereP appends storage-level predicates to the WeightMutation builder. Using this method,
// users can use type-assertion to append predicates that do not depend on any generated package.
func (m *WeightMutation) WhereP(ps ...func(*sql.Selector)) {
	p := make([]predicate.Weight, len(ps))
	for i := range ps {
		p[i] = ps[i]
	}
	m.Where(p...)
}

// Op returns the operation name.
func (m *WeightMutation) Op() Op {
	return m.op
}

// SetOp allows setting the mutation operation.
func (m *WeightMutation) SetOp(op Op) {
	m.op = op
}

// Type returns the node type of this mutation (Weight).
func (m *WeightMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *WeightMutation) Fields() []string {
	fields := make([]string, 0, 3)
	if m.userid != nil {
		fields = append(fields, weight.FieldUserid)
	}
	if m.timestamp != nil {
		fields = append(fields, weight.FieldTimestamp)
	}
	if m.value != nil {
		fields = append(fields, weight.FieldValue)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *WeightMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case weight.FieldUserid:
		return m.Userid()
	case weight.FieldTimestamp:
		return m.Timestamp()
	case weight.FieldValue:
		return m.Value()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *WeightMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case weight.FieldUserid:
		return m.OldUserid(ctx)
	case weight.FieldTimestamp:
		return m.OldTimestamp(ctx)
	case weight.FieldValue:
		return m.OldValue(ctx)
	}
	return nil, fmt.Errorf("unknown Weight field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WeightMutation) SetField(name string, value ent.Value) error {
	switch name {
	case weight.FieldUserid:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetUserid(v)
		return nil
	case weight.FieldTimestamp:
		v, ok := value.(time.Time)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetTimestamp(v)
		return nil
	case weight.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetValue(v)
		return nil
	}
	return fmt.Errorf("unknown Weight field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *WeightMutation) AddedFields() []string {
	var fields []string
	if m.adduserid != nil {
		fields = append(fields, weight.FieldUserid)
	}
	if m.addvalue != nil {
		fields = append(fields, weight.FieldValue)
	}
	return fields
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *WeightMutation) AddedField(name string) (ent.Value, bool) {
	switch name {
	case weight.FieldUserid:
		return m.AddedUserid()
	case weight.FieldValue:
		return m.AddedValue()
	}
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *WeightMutation) AddField(name string, value ent.Value) error {
	switch name {
	case weight.FieldUserid:
		v, ok := value.(int64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddUserid(v)
		return nil
	case weight.FieldValue:
		v, ok := value.(float64)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.AddValue(v)
		return nil
	}
	return fmt.Errorf("unknown Weight numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *WeightMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *WeightMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *WeightMutation) ClearField(name string) error {
	return fmt.Errorf("unknown Weight nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *WeightMutation) ResetField(name string) error {
	switch name {
	case weight.FieldUserid:
		m.ResetUserid()
		return nil
	case weight.FieldTimestamp:
		m.ResetTimestamp()
		return nil
	case weight.FieldValue:
		m.ResetValue()
		return nil
	}
	return fmt.Errorf("unknown Weight field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *WeightMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *WeightMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *WeightMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *WeightMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *WeightMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *WeightMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *WeightMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown Weight unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *WeightMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown Weight edge %s", name)
}
