// Code generated by ent, DO NOT EDIT.

package journal

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the journal type in the database.
	Label = "journal"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUserid holds the string denoting the userid field in the database.
	FieldUserid = "userid"
	// FieldTimestamp holds the string denoting the timestamp field in the database.
	FieldTimestamp = "timestamp"
	// FieldMeal holds the string denoting the meal field in the database.
	FieldMeal = "meal"
	// FieldFoodweight holds the string denoting the foodweight field in the database.
	FieldFoodweight = "foodweight"
	// EdgeFood holds the string denoting the food edge name in mutations.
	EdgeFood = "food"
	// Table holds the table name of the journal in the database.
	Table = "journals"
	// FoodTable is the table that holds the food relation/edge.
	FoodTable = "journals"
	// FoodInverseTable is the table name for the Food entity.
	// It exists in this package in order to avoid circular dependency with the "food" package.
	FoodInverseTable = "foods"
	// FoodColumn is the table column denoting the food relation/edge.
	FoodColumn = "food_journals"
)

// Columns holds all SQL columns for journal fields.
var Columns = []string{
	FieldID,
	FieldUserid,
	FieldTimestamp,
	FieldMeal,
	FieldFoodweight,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "journals"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"food_journals",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Journal queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUserid orders the results by the userid field.
func ByUserid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserid, opts...).ToFunc()
}

// ByTimestamp orders the results by the timestamp field.
func ByTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTimestamp, opts...).ToFunc()
}

// ByMeal orders the results by the meal field.
func ByMeal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMeal, opts...).ToFunc()
}

// ByFoodweight orders the results by the foodweight field.
func ByFoodweight(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFoodweight, opts...).ToFunc()
}

// ByFoodField orders the results by food field.
func ByFoodField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newFoodStep(), sql.OrderByField(field, opts...))
	}
}
func newFoodStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(FoodInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, FoodTable, FoodColumn),
	)
}
